# Generated by Django 2.2.5 on 2019-09-07 12:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro')),
                ('security', wagtail.core.fields.RichTextField(blank=True, verbose_name='Security')),
                ('environment', wagtail.core.fields.RichTextField(blank=True, verbose_name='Environment')),
                ('fire', wagtail.core.fields.RichTextField(blank=True, verbose_name='Fire')),
                ('architectural', wagtail.core.fields.RichTextField(blank=True, verbose_name='architectural')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
