# Generated by Django 2.2.5 on 2019-09-10 11:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='architectural',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Environment'),
        ),
    ]
