# Generated by Django 2.1.15 on 2021-01-26 14:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='showcase',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
    ]
