# Generated by Django 2.1.15 on 2021-02-09 14:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0002_products_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='content',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Link header image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Link title', max_length=40, require=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Link overview', max_length=400, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(help_text='Internal page link', required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page is selected, will be used first (external)', required=False))])), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock()), ('caption', wagtail.core.blocks.CharBlock(label='Caption', required=False)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Right'), ('left', 'Left'), ('Center', 'Center')], label='Float', required=False)), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], label='Size', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='showcase',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Showcase'),
        ),
    ]
