# Generated by Django 2.1.15 on 2021-02-09 14:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0003_auto_20210209_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='content',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Link header image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Link title', max_length=40, require=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Link overview', max_length=400, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(help_text='Internal page link', required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page is selected, will be used first (external)', required=False))]))], blank=True, null=True),
        ),
    ]
