# Generated by Django 2.1.15 on 2021-02-09 15:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0005_auto_20210209_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='showcase',
            field=wagtail.core.fields.StreamField([('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock()), ('caption', wagtail.core.blocks.CharBlock(label='Caption', required=False)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Right'), ('left', 'Left'), ('Center', 'Center')], label='Float', required=False)), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('half', 'Half')], label='Size', required=False))]))], blank=True, null=True),
        ),
    ]
