# Generated by Django 2.1.15 on 2021-04-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0006_auto_20210209_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('product_picture', models.ImageField(default='default profile pic1.png', upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('application', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('specification', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('finish', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('standards', models.TextField(blank=True, default='', max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='product',
            name='heading',
            field=models.ForeignKey(blank=True, default='', help_text='Choose a group this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='DEMOAPP.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
