# Generated by Django 2.1.15 on 2021-05-04 07:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0007_auto_20210427_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicing',
            name='intro',
            field=wagtail.core.fields.StreamField([('intro', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add your detail', required=False))]))], blank=True, null=True),
        ),
    ]
