# Generated by Django 2.1.15 on 2021-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0008_servicing_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
