# Generated by Django 2.1.15 on 2021-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0009_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
    ]
