# Generated by Django 2.1.15 on 2021-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0010_auto_20210504_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
