# Generated by Django 2.1.15 on 2021-05-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0011_auto_20210504_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='default profile pic1.png', upload_to='images/'),
        ),
    ]
