# Generated by Django 2.1.15 on 2021-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0012_auto_20210504_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='default profile pic1.png', upload_to=''),
        ),
    ]
