# Generated by Django 2.1.15 on 2021-05-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('DEMOAPP', '0015_auto_20210504_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doorsectional',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='doorspeed',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='othercrimeguardscreen',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='otherfortresstrellidor',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='otherloadingbays',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='otherpartitionscreens',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='othersecuritygates',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='shutterscommercial',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='shuttersfirecurtains',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='shuttersfireshutters',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='shuttersindustrial',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='shuttersinsulated',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='shutterssmokecurtains',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DoorSectional',
        ),
        migrations.DeleteModel(
            name='DoorSpeed',
        ),
        migrations.DeleteModel(
            name='OtherCrimeGuardScreen',
        ),
        migrations.DeleteModel(
            name='OtherFortressTrellidor',
        ),
        migrations.DeleteModel(
            name='OtherLoadingBays',
        ),
        migrations.DeleteModel(
            name='OtherPartitionScreens',
        ),
        migrations.DeleteModel(
            name='OtherSecurityGates',
        ),
        migrations.DeleteModel(
            name='ShuttersCommercial',
        ),
        migrations.DeleteModel(
            name='ShuttersFireCurtains',
        ),
        migrations.DeleteModel(
            name='ShuttersFireShutters',
        ),
        migrations.DeleteModel(
            name='ShuttersIndustrial',
        ),
        migrations.DeleteModel(
            name='ShuttersInsulated',
        ),
        migrations.DeleteModel(
            name='ShuttersSmokeCurtains',
        ),
    ]
