# Generated by Django 2.1.15 on 2021-05-04 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0016_auto_20210504_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
