# Generated by Django 2.1.15 on 2021-05-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0017_product_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='extra',
            new_name='information',
        ),
    ]
