# Generated by Django 2.1.15 on 2021-05-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0018_auto_20210504_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='application',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='standards',
        ),
    ]
